
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Button btnFind;
	
	private global::Gtk.Entry edtQuery;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnFind = new global::Gtk.Button ();
		this.btnFind.CanFocus = true;
		this.btnFind.Name = "btnFind";
		this.btnFind.UseStock = true;
		this.btnFind.UseUnderline = true;
		this.btnFind.Label = "gtk-find";
		this.hbox1.Add (this.btnFind);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnFind]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.edtQuery = new global::Gtk.Entry ();
		this.edtQuery.CanFocus = true;
		this.edtQuery.Name = "edtQuery";
		this.edtQuery.Text = global::Mono.Unix.Catalog.GetString ("Kate  Upton  ");
		this.edtQuery.IsEditable = true;
		this.edtQuery.InvisibleChar = '●';
		this.hbox1.Add (this.edtQuery);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edtQuery]));
		w2.Position = 1;
		this.vbox1.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnFind.Clicked += new global::System.EventHandler (this.OnBtnFindClicked);
	}
}
