
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.Notebook notebook;
	
	private global::Gtk.VBox vbox4;
	
	private global::Gtk.HBox hbox1;
	
	private global::Gtk.Entry edtQuery;
	
	private global::Gtk.Button btnFind;
	
	private global::superiorpics.Gallery forumsGallery;
	
	private global::Gtk.Label label3;
	
	private global::superiorpics.Gallery galleryPreview;
	
	private global::Gtk.Label label5;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.BorderWidth = ((uint)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.notebook = new global::Gtk.Notebook ();
		this.notebook.CanFocus = true;
		this.notebook.Name = "notebook";
		this.notebook.CurrentPage = 1;
		this.notebook.ShowBorder = false;
		this.notebook.Scrollable = true;
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.edtQuery = new global::Gtk.Entry ();
		this.edtQuery.CanFocus = true;
		this.edtQuery.Name = "edtQuery";
		this.edtQuery.Text = global::Mono.Unix.Catalog.GetString ("Alison Brie");
		this.edtQuery.IsEditable = true;
		this.edtQuery.InvisibleChar = '●';
		this.hbox1.Add (this.edtQuery);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.edtQuery]));
		w1.Position = 0;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnFind = new global::Gtk.Button ();
		this.btnFind.CanFocus = true;
		this.btnFind.Name = "btnFind";
		this.btnFind.UseStock = true;
		this.btnFind.UseUnderline = true;
		this.btnFind.Label = "gtk-find";
		this.hbox1.Add (this.btnFind);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnFind]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		this.vbox4.Add (this.hbox1);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox1]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.forumsGallery = new global::superiorpics.Gallery ();
		this.forumsGallery.Events = ((global::Gdk.EventMask)(256));
		this.forumsGallery.Name = "forumsGallery";
		this.vbox4.Add (this.forumsGallery);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.forumsGallery]));
		w4.Position = 1;
		this.notebook.Add (this.vbox4);
		// Notebook tab
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Search");
		this.notebook.SetTabLabel (this.vbox4, this.label3);
		this.label3.ShowAll ();
		// Container child notebook.Gtk.Notebook+NotebookChild
		this.galleryPreview = new global::superiorpics.Gallery ();
		this.galleryPreview.Events = ((global::Gdk.EventMask)(256));
		this.galleryPreview.Name = "galleryPreview";
		this.notebook.Add (this.galleryPreview);
		global::Gtk.Notebook.NotebookChild w6 = ((global::Gtk.Notebook.NotebookChild)(this.notebook [this.galleryPreview]));
		w6.Position = 1;
		// Notebook tab
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Gallery");
		this.notebook.SetTabLabel (this.galleryPreview, this.label5);
		this.label5.ShowAll ();
		this.vbox1.Add (this.notebook);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.notebook]));
		w7.Position = 0;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 870;
		this.DefaultHeight = 540;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnFind.Clicked += new global::System.EventHandler (this.OnBtnFindClicked);
	}
}
