
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class ImageLoader
	{
		private global::Gtk.EventBox eventbox1;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Alignment alignment1;
		
		private global::superiorpics.ImageEx image;
		
		private global::Gtk.HBox buttons;
		
		private global::Gtk.Alignment alignment3;
		
		private global::Gtk.Button btnSave;
		
		private global::Gtk.Button button1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.ImageLoader
			global::Stetic.BinContainer.Attach (this);
			this.Name = "superiorpics.ImageLoader";
			// Container child superiorpics.ImageLoader.Gtk.Container+ContainerChild
			this.eventbox1 = new global::Gtk.EventBox ();
			this.eventbox1.Name = "eventbox1";
			// Container child eventbox1.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.image = new global::superiorpics.ImageEx ();
			this.image.Name = "image";
			this.alignment1.Add (this.image);
			this.vbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.buttons = new global::Gtk.HBox ();
			this.buttons.Name = "buttons";
			this.buttons.Spacing = 6;
			// Container child buttons.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.buttons.Add (this.alignment3);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.buttons [this.alignment3]));
			w3.Position = 0;
			// Container child buttons.Gtk.Box+BoxChild
			this.btnSave = new global::Gtk.Button ();
			this.btnSave.CanFocus = true;
			this.btnSave.Name = "btnSave";
			this.btnSave.UseStock = true;
			this.btnSave.UseUnderline = true;
			this.btnSave.Label = "gtk-save";
			this.buttons.Add (this.btnSave);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.buttons [this.btnSave]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child buttons.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseStock = true;
			this.button1.UseUnderline = true;
			this.button1.Label = "gtk-remove";
			this.buttons.Add (this.button1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.buttons [this.button1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.buttons);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.buttons]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			this.eventbox1.Add (this.vbox1);
			this.Add (this.eventbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnSave.Clicked += new global::System.EventHandler (this.OnBtnSaveClicked);
		}
	}
}
