
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class Gallery
	{
		private global::Gtk.VBox vbox7;
		
		private global::Gtk.ScrolledWindow scrolledwindow2;
		
		private global::superiorpics.ResponsiveGrid grid;
		
		private global::Gtk.HBox hBottom;
		
		private global::Gtk.Button btnPrevious;
		
		private global::Gtk.ComboBox cmbPage;
		
		private global::Gtk.Button btnNext;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.Gallery
			global::Stetic.BinContainer.Attach (this);
			this.Name = "superiorpics.Gallery";
			// Container child superiorpics.Gallery.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.grid = new global::superiorpics.ResponsiveGrid ();
			this.grid.Events = ((global::Gdk.EventMask)(256));
			this.grid.Name = "grid";
			w1.Add (this.grid);
			this.scrolledwindow2.Add (w1);
			this.vbox7.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.scrolledwindow2]));
			w4.Position = 0;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hBottom = new global::Gtk.HBox ();
			this.hBottom.Name = "hBottom";
			this.hBottom.Spacing = 6;
			// Container child hBottom.Gtk.Box+BoxChild
			this.btnPrevious = new global::Gtk.Button ();
			this.btnPrevious.CanFocus = true;
			this.btnPrevious.Name = "btnPrevious";
			this.btnPrevious.UseUnderline = true;
			this.btnPrevious.Label = global::Mono.Unix.Catalog.GetString ("<<");
			this.hBottom.Add (this.btnPrevious);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hBottom [this.btnPrevious]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hBottom.Gtk.Box+BoxChild
			this.cmbPage = new global::Gtk.ComboBox ();
			this.cmbPage.Name = "cmbPage";
			this.cmbPage.AddTearoffs = true;
			this.hBottom.Add (this.cmbPage);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hBottom [this.cmbPage]));
			w6.Position = 1;
			// Container child hBottom.Gtk.Box+BoxChild
			this.btnNext = new global::Gtk.Button ();
			this.btnNext.CanFocus = true;
			this.btnNext.Name = "btnNext";
			this.btnNext.UseUnderline = true;
			this.btnNext.Label = global::Mono.Unix.Catalog.GetString (">>");
			this.hBottom.Add (this.btnNext);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hBottom [this.btnNext]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox7.Add (this.hBottom);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hBottom]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			this.Add (this.vbox7);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.cmbPage.Changed += new global::System.EventHandler (this.OnCmbPageChanged);
		}
	}
}
