
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class ResponsiveGrid
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.ResponsiveGrid
			global::Stetic.BinContainer.Attach (this);
			this.Name = "superiorpics.ResponsiveGrid";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
