
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class RandomCelebs
	{
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.Button btnRandom;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.RandomCelebs
			global::Stetic.BinContainer.Attach (this);
			this.Name = "superiorpics.RandomCelebs";
			// Container child superiorpics.RandomCelebs.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.btnRandom = new global::Gtk.Button ();
			this.btnRandom.CanFocus = true;
			this.btnRandom.Name = "btnRandom";
			this.btnRandom.UseUnderline = true;
			this.btnRandom.Label = global::Mono.Unix.Catalog.GetString ("Random");
			this.vbox1.Add (this.btnRandom);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.btnRandom]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnRandom.Clicked += new global::System.EventHandler (this.OnBtnRandomClicked);
		}
	}
}
