
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class WindowList
	{
		private global::Gtk.VBox list;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.WindowList
			this.Name = "superiorpics.WindowList";
			this.Title = global::Mono.Unix.Catalog.GetString ("WindowList");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child superiorpics.WindowList.Gtk.Container+ContainerChild
			this.list = new global::Gtk.VBox ();
			this.list.Name = "list";
			this.list.Spacing = 6;
			this.Add (this.list);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 248;
			this.DefaultHeight = 103;
			this.Show ();
		}
	}
}
