
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class FullImagePreview
	{
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::superiorpics.ImageLoader imageloader;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.FullImagePreview
			this.Name = "superiorpics.FullImagePreview";
			this.Title = global::Mono.Unix.Catalog.GetString ("FullImagePreview");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child superiorpics.FullImagePreview.Gtk.Container+ContainerChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w1 = new global::Gtk.Viewport ();
			w1.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.imageloader = new global::superiorpics.ImageLoader ();
			this.imageloader.Events = ((global::Gdk.EventMask)(256));
			this.imageloader.Name = "imageloader";
			this.imageloader.ShowButtons = false;
			w1.Add (this.imageloader);
			this.scrolledwindow1.Add (w1);
			this.Add (this.scrolledwindow1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 422;
			this.DefaultHeight = 513;
			this.Show ();
		}
	}
}
