
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class ResponsiveGrid
	{
		private global::Gtk.Table table;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.ResponsiveGrid
			global::Stetic.BinContainer.Attach (this);
			this.Name = "superiorpics.ResponsiveGrid";
			// Container child superiorpics.ResponsiveGrid.Gtk.Container+ContainerChild
			this.table = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table.Name = "table";
			this.table.RowSpacing = ((uint)(6));
			this.table.ColumnSpacing = ((uint)(6));
			this.Add (this.table);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
