
// This file has been generated by the GUI designer. Do not modify.
namespace superiorpics
{
	public partial class ImagePreviewWidget
	{
		private global::superiorpics.ImageLoader imageloader;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget superiorpics.ImagePreviewWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "superiorpics.ImagePreviewWidget";
			// Container child superiorpics.ImagePreviewWidget.Gtk.Container+ContainerChild
			this.imageloader = new global::superiorpics.ImageLoader ();
			this.imageloader.Events = ((global::Gdk.EventMask)(256));
			this.imageloader.Name = "imageloader";
			this.imageloader.ShowButtons = false;
			this.Add (this.imageloader);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
